### ISSUE TITLE
issue: wp-rest-polylang.php on line 49

### ISSUE THREAD

**Issue by AndreasEracleous** [dannyvaughton/wp-rest-polylang-pro#1]
Fatal error: Uncaught Error: Non-static method WP_REST_polylang::register_post_api_field() cannot be called statically in /opt/lampp/apps/wordpress/htdocs/wp-content/plugins/wp-rest-polylang-pro-master/wp-rest-polylang.php:49 Stack trace: #0 /opt/lampp/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(287): WP_REST_polylang::init(Object(WP_REST_Server)) #1 /opt/lampp/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /opt/lampp/apps/wordpress/htdocs/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #3 /opt/lampp/apps/wordpress/htdocs/wp-includes/rest-api.php(521): do_action('rest_api_init', Object(WP_REST_Server)) #4 /opt/lampp/apps/wordpress/htdocs/wp-includes/rest-api.php(347): rest_get_server() #5 /opt/lampp/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(287): rest_api_loaded(Object(WP)) #6 /opt/lampp/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #7 /opt/lampp/apps/wordpress/htdocs/wp-includes/plugin.php(551): WP_Hook->do_action(Array) #8 /opt/lampp/apps/wordpress/htdocs/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array) #9 /opt/lampp/apps/wordpress/htdocs/wp-includes/class-wp.php(745): WP->parse_request('') #10 /opt/lampp/apps/wordpress/htdocs/wp-includes/functions.php(1291): WP->main('') #11 /opt/lampp/apps/wordpress/htdocs/wp-blog-header.php(16): wp() #12 /opt/lampp/apps/wordpress/htdocs/index.php(17): require('/opt/lampp/apps...') #13 {main} thrown in /opt/lampp/apps/wordpress/htdocs/wp-content/plugins/wp-rest-polylang-pro-master/wp-rest-polylang.php on line 49

**Comment by AntonioMrqz** [comment]
Has there been any fix to this issue? Currently having the same problem
